[package]
name = "rpc_ipc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2", features = ["full"] }
quote = "1.0"
bincode = { version = "2.0.0-rc.3" }
